### ISSUE TITLE
 inconsistent naming of SVCall_IRQn accross families

### ISSUE THREAD

**Issue by dylad** [STMicroelectronics/cmsis-device-l1#1]
**Describe the bug**
There is an inconsistency in several ST families  regarding the SVC_IRQn naming (should be SVCall_IRQn).
This inconsistency affects F0, L0, L1, G0 as far as I can tell.
This value is defined in `IRQn_Type` typedef enum for instance [here](https://github.com/STMicroelectronics/cmsis_device_l1/blob/12a490498a1b5c21242169d1b0dcb84936a4b4d2/Include/stm32l151xc.h#L76)

Is there any plan to unify the name ?

Thanks for your help.
Regards,

**Comment by TOUNSTM** [comment]
ST Internal Reference: 180194

**Comment by KRASTM** [comment]
Fixed in commit f1665c78b60125cb97d1634364e0883bb8c2b7b7

**Comment by dylad** [comment]
Thanks for the fix !
